name: CD

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # To authenticate to GCP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name
        id: set-image-name
        run: echo "image_name=${{ vars.DOCKER_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.DOCKER_REPO_NAME }}/kimina-lean-server:$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build . -t "${{ steps.set-image-name.outputs.image_name }}"
        # --build-arg truc=${{ vars.TRUC}} 

      - name: "GCP auth"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ vars.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}"
          service_account: "${{ vars.SERVICE_ACCOUNT }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.DOCKER_REPO_REGION }}-docker.pkg.dev

      - name: Push Docker image
        run: docker push "${{ steps.set-image-name.outputs.image_name }}"

      - name: Create new instance template
        #   IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ steps.set-image-name.outputs.image_name }}"
        run: |
          TEMPLATE="kimina-tpl-${{ github.sha }}"
          IMAGE="${{ steps.set-image-name.outputs.image_name }}"
          REGION="${{ vars.DOCKER_REPO_REGION }}"
          gcloud compute instance-templates create-with-container $TEMPLATE \
            --container-image=$IMAGE \
            --container-restart-policy=on-failure \
            --container-stdin \
            --container-tty \
            --machine-type=n2-standard-16 \
            --region=$REGION \
            --boot-disk-size=50GB --boot-disk-type=pd-ssd \
            --tags=http-server,https-server,lb-health-check

      - name: Roll out rolling‑update to MIG
        run: |
          gcloud compute instance-groups managed rolling-action start-update ig-1 \
            --version=template=$TEMPLATE \
            --max-surge=1 \
            --max-unavailable=0 \
            --region=${{ vars.DOCKER_REPO_REGION }}

    #   - name: Deploy Docker image
    #     id: deploy
    #     uses: "google-github-actions/deploy-cloudrun@v2"
    #     with:
    #       image: "${{ steps.set-image-name.outputs.image_name }}"
    #       region: "${{ vars.DOCKER_REPO_REGION }}"
    #       service: kimina-lean-server
    #     #   flags: --port=3000